# Generated by Django 3.1.5 on 2021-01-26 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letterapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newletteruser',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
